version: "3"
services:
  postgres:
    platform: linux/arm64/v2
    image: frabczyn/erpmes:erppostgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
    ports:
      - '5432:5432'
    volumes:
      - ./create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
  eureka-server:
    image: frabczyn/erpmes:erpeureka64
    ports:
      - "9761:9761"
    depends_on:
      - postgres
  shop:
    image: frabczyn/erpmes:erpshop64
    ports:
      - "9080:9080"
    depends_on:
    - eureka-server
    - postgres
  communication:
    image: frabczyn/erpmes:erpcommunication64
    ports:
      - "9081:9081"
    depends_on:
      - eureka-server
      - postgres
  staff:
    image: frabczyn/erpmes:erpstaff64
    ports:
      - "9082:9082"
    depends_on:
      - eureka-server
      - postgres
  production:
    image: frabczyn/erpmes:erpproduction64
    ports:
      - "9083:9083"
    depends_on:
      - eureka-server
      - postgres
