version: "3"
services:
  postgres:
    platform: linux/amd64
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
    ports:
      - '5432:5432'
    volumes:
      - ./create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
  eureka-server:
    platform: linux/amd64
    image: frabczyn/erpmes:erpeureka64
    ports:
      - "9761:9761"
    depends_on:
      - postgres
  shop:
      platform: linux/amd64
      image: frabczyn/erpmes:erpshop64v2
      ports:
        - "9080:9080"
      depends_on:
        - eureka-server
        - postgres
  communication:
      platform: linux/amd64
      image: frabczyn/erpmes:erpcommunication64v2
      ports:
        - "9081:9081"
