version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
    ports:
      - '5432:5432'
    volumes:
      - ./create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
  eureka-server:
    image: eureka:latest
    ports:
      - "9761:9761"
    depends_on:
      - postgres
  shop:
    image: shop:latest
    ports:
      - "9080:9080"
    depends_on:
    - eureka-server
    - postgres
  communication:
    image: communication:latest
    ports:
      - "9081:9081"
    depends_on:
      - eureka-server
      - postgres
  staff:
    image: staff:latest
    ports:
      - "9082:9082"
    depends_on:
      - eureka-server
      - postgres
  production:
    image: production:latest
    ports:
      - "9083:9083"
    depends_on:
      - eureka-server
      - postgres
